# Site identity
title: "Benjamin C. Buchmuller"
author: "Benjamin Buchmuller"
description: "Personal research homepage"

# Site settings
url: "https://benjbuch.github.io"
baseurl: ""
lang: "en"
timezone: "ET"

# Profile
owner:
  name: "Benjamin Buchmuller"
  title: "Senior Research Associate"
  affiliation: "Princeton University"
  orcid: "https://orcid.org/0000-0002-4915-5949"
  scholar: "https://scholar.google.com/citations?user=H3kb0RQAAAAJ"
  github: "https://github.com/benjbuch"
  linkedin: "https://www.linkedin.com/in/benjamin-buchmuller/"
social:
  name: "Benjamin Buchmuller"
  links:
    - "https://www.researchgate.net/profile/Benjamin-Buchmuller"
    - "https://scholar.google.com/citations?user=H3kb0RQAAAAJ"
    - "https://github.com/benjbuch"
    - "https://www.linkedin.com/in/benjamin-buchmuller/"

# Collections
collections:
  sections:
    output: true
    permalink: /sections/:name/

# Site rendering
theme: null
permalink: pretty

# Markdown and code highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    line_numbers: false

# SASS/CSS
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
      lang: "en"
      # image: "/assets/img/og.jpg"  # default OpenGraph image
  - scope:
      path: ""
      type: "sections"
    values:
      layout: card

# Keep builds tidy
include:
  - robots.txt.liquid

exclude:
  - .github/
  - Makefile
  - node_modules/
  - README.md
  - scripts/
  - vendor/

# Plugins supported on GitHub Pages
plugins:
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-seo-tag

# Prevent GitHub Pages from rebuilding things twice
future: true
lsi: false
safe: true